// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6zNQRij19me_3TCmeGp_3TaqXcKorjw',
    appId: '1:479654486767:web:805e975d55ddd17078711a',
    messagingSenderId: '479654486767',
    projectId: 'furniture-28bab',
    authDomain: 'furniture-28bab.firebaseapp.com',
    storageBucket: 'furniture-28bab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBW1jBAHZTDdWgKlyovsyY3PeAxHMIqg',
    appId: '1:479654486767:android:0e5c9f501422144878711a',
    messagingSenderId: '479654486767',
    projectId: 'furniture-28bab',
    storageBucket: 'furniture-28bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VpcS_Wul_bpbay8QaMgg-wqdqvRFHGE',
    appId: '1:479654486767:ios:06666ebf05f9b4fc78711a',
    messagingSenderId: '479654486767',
    projectId: 'furniture-28bab',
    storageBucket: 'furniture-28bab.appspot.com',
    iosClientId: '479654486767-0chf0i3c6upqce19cbrr599n8mef4qr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.furniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VpcS_Wul_bpbay8QaMgg-wqdqvRFHGE',
    appId: '1:479654486767:ios:06666ebf05f9b4fc78711a',
    messagingSenderId: '479654486767',
    projectId: 'furniture-28bab',
    storageBucket: 'furniture-28bab.appspot.com',
    iosClientId: '479654486767-0chf0i3c6upqce19cbrr599n8mef4qr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.furniture',
  );
}
